export const ALERT_ACTIONS = {
    FETCH_ALERTS: 'FETCH_ALERTS',
    SET_ALERTS: 'SET_ALERTS',
    CREATE_ALERT: 'CREATE_ALERT',
    DELETE_ALERT: 'DELETE_ALERT',
    REQUEST_START: 'REQUEST_START_ALERT_ACTION',
    REQUEST_DONE: 'REQUEST_DONE_ALERT_ACTION',
    ALERT_ACTION_FAILED: 'ALERT_ACTION_FAILED',
};